/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scalanim_NativeWrapper__ */

#ifndef _Included_scalanim_NativeWrapper__
#define _Included_scalanim_NativeWrapper__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scalanim_NativeWrapper__
 * Method:    plus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_scalanim_NativeWrapper_00024_plus
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
