/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scalanim_NativeWrapperNim__ */

#ifndef _Included_scalanim_NativeWrapperNim__
#define _Included_scalanim_NativeWrapperNim__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scalanim_NativeWrapperNim__
 * Method:    addOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_scalanim_NativeWrapperNim_00024_addOne
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
