/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class scalanim_NativeWrapperCpp__ */

#ifndef _Included_scalanim_NativeWrapperCpp__
#define _Included_scalanim_NativeWrapperCpp__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     scalanim_NativeWrapperCpp__
 * Method:    addOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_scalanim_NativeWrapperCpp_00024_addOne
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
